<?php
session_start();
?>


<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Mi Pueblo — Portada</title>
  <link rel="stylesheet" href="./CSS/styles.css">
</head>

<body>
  <header>
    <div class="container nav">
      <a href="index.php">
        <span>Mi Pueblo</span>
      </a>
      <nav>
        <ul>
          <li><a href="index.php" class="active" aria-current="page">Inicio</a></li>
          <li><a href="./views/noticias.php">Noticias</a></li>
         <?php if (!isset($_SESSION['user'])): ?>
    <!-- VISITANTE -->
    <li><a href="./views/registro.php">Registro</a></li>
    <li><a href="./views/login.php">Login</a></li>

<?php else: ?>

    <?php if ($_SESSION['user']['rol'] === 'admin'): ?>
        <li><a href="./views/usuario-administracion.php">Usuarios-administracion</a></li>
        <li><a href="./views/citaciones-administracion.php">Citaciones-administracion</a></li>
        <li><a href="./views/noticias-administracion.php">Noticias-administracion</a></li>
    <?php endif; ?>
    <li><a href="./views/citaciones.php">Citaciones</a></li>
    <li><a href="./views/perfil.php">Perfil</a></li>
    <li><a href="./views/cerrarSesion.php">Cerrar sesión</a></li>

<?php endif; ?>



        </ul>
      </nav>
    </div>
  </header>

  <main id="contenido">
    <div class="container">
      <section>
        <div>
          <div>
            <h1>Bienvenido a Mi Pueblo</h1>
            <h2>Hitoria</h2>

            <h3>Introducción</h3>
            <p>El Coronil es un pueblo de la Campiña sevillana situado a 54 km (40 min) de la capital. Muy bien comunicado, posee una localización estratégica entre las provincias de Sevilla, Cádiz y Málaga.
              Su entorno paisajístico está formado por las suaves ondulaciones propias de la campiña y aproximándonos a la provincia de Cádiz hallamos la topografía y vegetación propias de la presierra que nos conduce a la Vía Verde. Las principales vías fluviales que cruzan el término municipal son el Arroyo Salado y el río Guadalete.
              Dependiendo de la época en la que nos encontremos podemos contemplar un mar de verdes u ocres trigales, el contraste de los girasoles o el sosiego de la imagen parda de la tierra calma.
              Pueblo de tradiciones, rica gastronomía y gente hospitalaria. En incipiente desarrollo turístico y empresarial, cuenta con la instalación solar fotovoltaica mayor de Andalucía y una incipiente industria agroalimentaria con tecnología punta.</p><br>


            <h3>Historia de la villa de El Coronil</h3>
            <p>Basado en textos del historiador local Antonio Ruiz Pérez.
              Los primeros asentamientos humanos en esta zona de la campiña corresponden al periodo del Calcolítico en torno al 2300 a. C. y se dan en lugares con condiciones favorables como pueden ser la cercanía de manantiales de agua para favorecer su abastecimiento, enclaves elevados que faciliten la defensa, o en zonas de fácil comunicación que permitan el comercio. Son asentamientos pequeños en extensión que se benefician de la riqueza agrícola de la zona, de ahí los útiles en piedra pulimentada encontrados y los restos de animales domesticados, así como la numerosa y variada cerámica. Destacan los yacimientos de la Fresnadilla, el Tesorillo, la Piedra Hincada o las Aguzaderas entre otros muchos, aunque sin duda los dos principales estarían situados hoy fuera del término municipal coronileño pero si bastante cerca del actual núcleo urbano de El Coronil. Son los yacimientos del Molino Pintado y del Cerro El Casar, donde también son muy abundantes los restos ibéricos, e incluso se piensa que el propio castillo de El Coronil está asentado sobre una antigua atalaya de origen celta que permitiría controlar las rutas de comunicación que cruzaban por esta zona.
              Pero sin duda, será el periodo romano el más importante, no sólo por un aumento considerable del poblamiento del lugar, sino también por los numerosos asentamientos encontrados y la abundancia de útiles y monedas de esta época. Así la riqueza agrícola de la zona poblará sus campos de villas romanas que actuarán como núcleos de explotación agrícola y ganadera y que tendrán su esplendor en el siglo II d. C. Así el propio yacimiento de El Casar, nombrado anteriormente, se convertirá en la ciudad romana de Salpensa que adquirirá la categoría de municipio romano, acuñando su propia moneda desde época Flavia y de la que se han conservado sus propias leyes municipales. Otro enclave cercano al Coronil será el del Tesorillo el que por su riqueza minera también destacó en época de Adriano. Sus habitantes denominados callenses serían los primitivos pobladores de El Coronil llegando a rehacer la arruinada atalaya celta existente en el pueblo. Tras la crisis general del siglo III d. C., y de la que no se libró tampoco esta zona, llegamos al periodo musulmán en el que Salpensa perdería su peso anterior hasta prácticamente su desaparición igual que la República Callense que sería destruida por los invasores. Poco sabemos del periodo de dominación musulmana, siendo lo más destacable la construcción de sus dos castillos, el de la Villa y el de las Aguzaderas, ambos muy transformados después tras la reconquista cristiana, y que responden al proceso de encastillamiento que vivió toda la campiña, por el cual la población tendía a concentrarse junto a pequeños enclaves fortificados donde pudiera encontrar refugio en caso de peligro. Esto nos indica la presencia de una pequeña población en la zona como también lo atestiguan los restos arqueológicos encontrados tales como lucernas, jarras, ladrillos o monedas.
              Sin embargo, el verdadero origen del núcleo poblacional actual de El Coronil hay que buscarlo tras la Reconquista Cristiana y estuvo muy condicionado por la existencia de la frontera con el Reino Nazarita de Granada. Era la llamada Banda Morisca, un espacio territorial conquistado en tiempos de Fernando III el Santo, en el que se daban continuos saqueos y escaramuzas por las tropas musulmanas. Esta situación de continuo peligro llevó a que la zona permaneciese prácticamente despoblada y la única población existente se agrupaba en torno a torres o edificios amurallados en los cuales podían refugiarse ante la llegada del enemigo islámico. El escaso poblamiento llevó a que la Iglesia, las Ordenes Militares y la nobleza fuesen adquiriendo en la zona abundantes propiedades que para sacarles el mayor partido y obtener rentas debían repoblar. Por ello, lo primero que hicieron estos señores fue atraer población a la zona a fin de que cultivasen dichas tierras y pudiesen cobrar tributos, a la vez que defendían el territorio. Para atraer población a una zona tan peligrosa como ésta les ofrecían abundantes beneficios, tales como exenciones de impuestos y parcelas de tierras en propiedad para su cultivo.
              Será uno de estos linajes, el que va a adquirir el territorio donde hoy se encuentra la villa. Su nuevo señor Ruy Pérez de Esquivel intentará sacar partido a su nueva propiedad y así el 25 de abril de 1381 obtiene del Rey Juan I una Real Cédula por la cual puede repoblar el lugar con quince vecinos. Este es el origen de la actual villa coronileña. Para su defensa reconstruirá la fortaleza existente en el lugar que desde hacía tiempo se encontraba abandonada y en ruina. Será el actual castillo de El Coronil. Sus primeros habitantes serán a la vez agricultores y soldados defendiendo esta zona de los enemigos musulmanes. Pero las continuas cabalgadas y escaramuzas de los árabes hicieron que El Coronil casi se despoblase y será con sus nuevos señores, los Adelantados de Andalucía, con los que se supere este bache y se obtenga una fuerte pujanza económica. Es ahora cuando se unen los dos territorios que forman su actual término municipal, el de las Aguzaderas y el del Coronil, pues los Ribera ya poseían el primer territorio por cesión del Rey Juan I y que ahora al comprar El Coronil en 1419 formarían un único territorio de señorío. También se trasladará a la población existente en las Aguzaderas para concentrarla en El Coronil, consolidando y ampliando su poblamiento. Así, en el año 1500 el municipio tendrá 32 vecinos ampliándose su casco urbano y obteniéndose del monarca Juan II un privilegio para celebrar dos ferias anuales de treinta días. Igualmente se construirá ahora su templo parroquial. Este auge también afectará a sus tierras pues se abren nuevos caminos y pozos, se plantan nuevos cultivos y se roturan nuevas tierras.
              Durante los siglos siguientes, El Coronil seguirá prosperando pues sus señores se preocuparán por el buen gobierno y administración de estas tierras llegando a pasar largas temporadas en su castillo-fortaleza que convirtieron en un auténtico palacio, mientras que el Castillo de las Aguzaderas a unos tres kilómetros aproximadamente de la Villa en dirección a Montellano quedó como un enclave de defensa avanzado en la frontera. Sin embargo, ya en el siglo XVII comenzará a decaer este auge pues sus señores dejarán de preocuparse por estas posesiones al marchar a la Corte y ostentar importantes cargos políticos dejando su administración en manos de funcionarios ineficaces para estas tareas de gobierno, por lo que las arbitrariedades y la corrupción comenzarán a extenderse, enemistándose poco a poco la población con sus señores. A esto se une la crisis general que vive el país y las epidemias periódicas que golpean a la zona por lo que se tuvo que crear un hospital para atender a los afectados en las afueras del pueblo, concretamente en la Ermita de la Veracruz. De todas formas, podemos decir, que El Coronil logró salir milagrosamente de estas epidemias que afectaron a los alrededores. Tal hecho aumentó el fervor por San Roque al que creían su protector por lo que el pueblo junto con sus autoridades le ofrecieron solemnes funciones religiosas y de acción de gracias, culminando estos hechos con el nombramiento como patrón de la Villa en 1649.
              La población decrecerá y sólo a finales del siglo XVII se iniciará una tímida recuperación que se intensificará durante el XVIII. Durante este siglo el capitalismo dará lugar a la aparición de grandes latifundios por la usurpación ilegal de baldíos y tierras comunales que provocaron un fuerte aumento de los jornaleros que ya sobrepasaban el 70 % de la población coronileña. En un principio se repartirán tierras entre los habitantes más pobres de la Villa pero el control que los terratenientes tenían sobre el gobierno municipal favorecerá el retorno de éstas al control municipal y su subasta en grandes lotes lo que les permitía su apropiación legal. Esto llevó a que el malestar se intensificase entre los vecinos intentando repetidamente salir del poder señorial que en estos momentos estaba representado por los Duques de Medinaceli a los que se habían unido en matrimonio los Enriquez de Ribera, sus anteriores señores, y pasar a ser tierras de realengo. Igualmente, durante este siglo XVII se establecerá en El Coronil la Orden de los Carmelitas Descalzos pues fundan un convento en la Villa gracias a la donación de unos bienes en testamento por Don Miguel Martín Pescador. El propio Arzobispo de Sevilla, Don Jaime de Palafox y Cardona, visitó El Coronil para comprobar si era adecuada tal fundación, dando finalmente su consentimiento en 1687. Este tendría la advocación de San Miguel y quedaría ubicado junto a la Ermita de la Veracruz que ya existía desde finales del siglo XV en las afueras del pueblo. Esta fundación religiosa poseerá bienes propios para mantener hasta veinte religiosos.
              En el siglo XVIII se intensificaron los deseos de los campesinos por obtener tierras en propiedad, pues éstas pertenecían en su mayor parte al Duque de Medinaceli. Los arrendamientos subían de precio y el paro se extendía por lo que el Concejo Municipal tuvo que repartir trigo entre los vecinos más pobres para evitar que el hambre hiciera su aparición. Todo ello contrasta con el crecimiento económico y demográfico de la época, que será general en toda la zona llegando El Coronil a tener en el año 1786 una población de 2064 habitantes, según el Censo de Floridablanca. También aumentará la producción agrícola pues se ponen en cultivo nuevas tierras antes dedicadas a pastos, pero el atraso técnico seguía siendo un hecho y la influencia de la meteorología con periodos de sequía o de inundaciones arruinaban bastantes cosechas. Esto y la falta de tierras obligó a muchos coronileños a trabajar en las villas limítrofes por lo que la tensión aumentó comenzando a hacerse algunos repartos puntuales que en nada calmaron a su población sino que la animaron a pedir más tierras en propiedad dándose continuos incidentes y pleitos que se extendieron hasta mediados del siglo XIX.
              Pero también en el siglo XVIII sufrirá El Coronil algunos movimientos sísmicos que afectaron a algunos de sus edificios más notables como su Ayuntamiento o su Templo Parroquial. Este último será ahora remodelado y ampliado hasta configurar la actual imagen neoclásica. Se abrirán nuevas calles como ocurrió con las calles Vereda, Sol y Sevilla, y se establecerá la típica casa alargada de El Coronil con el objetivo de poder alojar a las tropas que frecuentemente pasaban por el pueblo en dirección al Estrecho de Gibraltar. Esto se debió a una orden dada por su Concejo Municipal en 1738. También se construirá la Capilla de los Remedios y se establecerá la Escuela Pública de la Villa en el Palacete de Don Diego Quebrado, ubicado en la actual calle Martínez Benjumea, y que contaba con dos aulas, una para la instrucción primaria y otra como Cátedra de Latinidad. Esta fundación de enseñanza pública se debió a los numerosos bienes dejados en testamento por Don Diego Quebrado y su esposa, Dña. Mariana de la Calle, funcionando con regularidad hasta 1808, en que dichos bienes fueron embargados por el Estado ante la crisis económica que vivía el país.
              Durante el siglo XIX el municipio se vio afectado por las nuevas ideas liberales y revolucionarias traídas por la invasión napoleónica. El Coronil va a lograr salir definitivamente de la jurisdicción señorial derribándose los escudos señoriales de sus edificios públicos y quedando bajo el poder de su rica oligarquía agraria que desde hacía tiempo presionaba por hacerse con el control de la Villa. El final del dominio señorial dividió a sus habitantes en dos grandes bandos, los duquistas partidarios de la vuelta al Antiguo Régimen y al dominio ducal sobre la Villa, y los terreros partidarios de implantar libertades y del reparto de tierras entre los vecinos. Esto último dominará gran parte de la Historia del Municipio durante esta centuria. Los pleitos sobre la propiedad de las tierras del Señor Duque se sucedieron, primero por las que habían sido usurpadas por los señores a lo largo de los siglos, y luego por la totalidad de ellas, por lo que el enfrentamiento entre los dos bandos llevó a fuertes disturbios y a problemas de orden público. Por otro lado, la fuerte corrupción existente en la Justicia, provocará que los sucesivos pleitos fuesen ganados por el Duque que influía en los jueces para que retrasasen o adelantasen los pleitos según si el momento político que vivía el país le fuese favorable o no. Así, una vez confirmada la propiedad de estas tierras en manos del Duque de Medinaceli, y puesto que la calma no llegaba, éste decidió vender en 1850 la totalidad de sus bienes en El Coronil, siendo sus grandes arrendatarios tradicionales los que las obtuvieron, consolidándose de este modo el actual estado de la propiedad en El Coronil en manos de grandes terratenientes, pues sólo algunos pequeños colonos lograrían obtener algunas porciones de tierra, siendo la familia de los Candau, los principales beneficiarios. Por otro lado, también sufrirá El Coronil la desamortización eclesiástica, perdiendo sus bienes algunas de sus cofradías y el Convento de los Carmelitas Descalzos de la Villa, cuyos miembros abandonaron el pueblo definitivamente. En resumen, podemos decir que El Coronil aprovechará la situación política nacional para solucionar su conflicto de la tierra. Así, a la primera etapa de pleitos, en la que se buscan soluciones jurídicas, le sigue la participación de los campesinos en la política apoyando a los grupos políticos más radicales, y finalmente al ver que estos partidos apenas apoyan al campesinado pues las manipulaciones electorales son continuas, este campesinado se hará anarquista utilizándose la huelga como principal medio de lucha. Esta situación perdurará hasta la Guerra Civil.
              El siglo XIX también traerá al Coronil un fuerte crecimiento demográfico, a pesar de que algunas epidemias como la de cólera de 1854 atacará duramente a la Villa, matando a más de 370 personas. Así, en 1898 se llegó a los 4773 habitantes. Este aumento del número de sus vecinos, en su mayoría jornaleros, abaratará la mano de obra bajando el nivel de vida, e impidiendo por tanto el desarrollo de la demanda que lleve a la industrialización de la zona. De ahí que siga siendo la agricultura su principal fuente de riqueza, destacando el trigo y sobre todo el olivar que tendrá ahora su mayor desarrollo hasta que a principios del XX sufra la competencia de otras grasas vegetales industriales más baratas. Se planifica también el crecimiento urbano del pueblo, se abren nuevas calles y se restauran los dos castillos que posee el municipio, finalizándose las obras en su parroquia. Igualmente se produce ahora el embellecimiento de su plaza pública y de su ayuntamiento.
              El siglo XX se inicia con una mala situación económica que se refleja en su sociedad, formada por un pequeño grupo de señoritos terratenientes que mantiene en la miseria al inmenso conjunto de la población. Ello provoca un aumento del bandolerismo. Así, en la zona va a actuar un famoso bandolero, el Pernales.
              Durante la Dictadura de Primo de Ribera El Coronil obtendrá nuevos servicios públicos como es el caso del alumbrado eléctrico, del servicio telefónico, así como del servicio de agua potable, instalándose en estos años las primeras fuentes públicas que poseerá el pueblo. Igualmente se expansionará el algodón y la remolacha azucarera como nuevos cultivos, uniéndose a los ya tradicionales de cereal y de olivar.
              La República llegará con una fuerte crisis agrícola pues la introducción de maquinaria agrícola reduce el trabajo de los jornaleros en las faenas del campo. Se agudizan por ello los conflictos sociales, reclamándose mejoras en las condiciones de vida y tierras en propiedad. La población comenzará a sindicarse por la influencia del socialismo, apareciendo de este modo la Casa del Pueblo, mientras que el anarquismo iría en detrimento. La tensión social se recrudecía impidiéndose la utilización de máquinas segadoras por los trabajadores mientras que los terratenientes las utilizaban cada vez más para reducir los costes salariales.
              En tal situación estalla la Guerra Civil y el día 31 de julio una columna armada entra en El Coronil tomando rápidamente los nacionales el poder municipal al mando del Capitán de Corbeta Don Ramón de Carranza, pues no se produjeron disturbios, sin embargo, pronto la represión hará su aparición con el fin de evitar el supuesto “peligro marxista”. Muchos coronileños fueron detenidos y fusilados y el hambre se extendió, por la guerra y por las malas cosechas del año.
              El gobierno municipal, al igual que el resto de la nación, estableció cartillas de racionamiento, iniciándose obras públicas para la mejora de las infraestructuras viarias y de sus calles con el fin de terminar con el paro. El latifundismo continuaba junto a una gran tranquilidad social por la fuerte represión existente ante cualquier sospecha de oposición al régimen. En el campo se extendía el cultivo del girasol, pues éste junto al del algodón y la remolacha permitían ofrecer muchos jornales. Igualmente, la construcción de la base aérea de Morón a finales de los años 50 abre las posibilidades de trabajo en el pueblo, pero las esperanzas pronto se esfumaron y ante la falta de trabajo, gran parte de su población se vio obligada a emigrar a las zonas más industrializadas del país, principalmente a Barcelona y en menor medida a Madrid y Sevilla. De ahí que entre el año 56 y el 75 El Coronil perdiera a la mitad de su población. Sólo la crisis de los 70 permite la vuelta de parte de esos emigrantes, mientras que los cultivos de girasol hacen de El Coronil uno de los principales productores del país, mecanizándose rápidamente todas sus tareas ante los grandes beneficios que reportaba. Aunque éste pronto quedó en manos de empresas aceiteras foráneas que impidieron crear fábricas para su transformación en la zona.
              Tras la enfermedad que sufrió el girasol, se buscaron nuevos cultivos alternativos como el espárrago. Se pretendía mejorar la situación del campo coronileño y el progreso económico de su población. Además este siglo supuso el mayor crecimiento de su casco urbano, pues a la primera barriada construida en el pueblo en los años 40 para grupos sociales de bajos ingresos, Barriada de Coca de la Piñera, le han seguido muchas otras ya en plena época democrática como la Barriada situada en el Llano de San Sebastián, conocida popularmente como de “Las Malvinas” y las ubicadas en la zona de El Carpio, entre otras, solucionando el problema de determinadas zonas de la localidad en las que vivían familias muy numerosas en condiciones inadecuadas. También se modernizaron sus infraestructuras y servicios que iban desde la construcción de rondas de circunvalación para evitar el tráfico pesado por el interior del pueblo, a un polideportivo con sus pistas de deporte y su piscina, su pabellón cubierto o su nuevo campo de fútbol, nuevos servicios educativos y sociales, instalaciones sanitarias y nuevas empresas que permitían augurar un futuro más esperanzador para sus habitantes.
              El nuevo siglo XXI supuso continuar con la tendencia del crecimiento de su casco urbano con nuevas barriadas en la zona del Convento y en la salida hacía Pilares, de iniciativa privada. Hoy El Coronil tiene una población aproximada de 5.000 habitantes y cuenta como principal vector de desarrollo con una apuesta decidida por las energías renovables y los cultivos alternativos. Como ejemplos, la instalación solar fotovoltaica mayor de Andalucía y una incipiente industria agroalimentaria con tecnología punta.
              Aunque la base de su economía continúa ligada a la producción agrícola, nos encontramos inmersos en un proceso de diversificación, con una clara apuesta por el comercio y empresariado local, y por la implantación de empresas foráneas que generen empleo en el municipio.
              En definitiva, el Coronil, hoy por hoy es una localidad muy orgullosa de su larga historia. Un pueblo de tradiciones, rico en cultura y gente hospitalaria, adaptado a los nuevos tiempos, en incipiente desarrollo turístico y empresarial.</p><br>

            <div>
              <a class=" btn btn1" href="https://www.pergeo.es/team/provincia-de-sevilla/">Topografia</a>
            </div>
          </div>
          <figure>
            <img src="https://picsum.photos/900/520?random=11" alt="Imagen">
          </figure>
        </div>
      </section>

      <section id="enlaces" class="section">
        <h2>Enlaces útiles</h2>
        <ul>
          <li><a href="https://developer.mozilla.org/es/docs/Web/HTML" target="_blank">MDN HTML</a></li>
          <li><a href="https://www.w3schools.com/html/" target="_blank">W3Schools HTML</a></li>
        </ul>
      </section>
    </div>
  </main>

  <footer>
    <p>&copy; <span id="year"></span> Mi Pueblo. Todos los derechos reservados.</p>
  </footer>



  <script src="./JS/script.js"></script>
</body>

</html>